### ISSUE TITLE
有两个翻译小建议

### ISSUE THREAD

**Issue by lianwensheng** [Z-Siqi/Clash-for-Windows_Chinese#110]
### 催更

1、不知道能否把“Clash 核心版本”翻译为“Clash 核心”，因为当核心版本名字过长，排版就会出现问题😂

![屏幕截图 2023-06-22 052030](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/36002202/ba1de2b8-2fb5-4b22-80b9-aecf020d3f42)

2、建议给CFW自带编辑器搜索功能的按钮提示增加个翻译😉

![屏幕截图 2023-06-22 052229](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/36002202/93b6896e-95d9-4e5e-a2f4-c2ed1bc723ce)

**Comment by lianwensheng** [comment]
还有一处忘记说了，当日记级别改成“警告”后，关闭CFW窗口重新打开，“警告”就会变回成英文“warn”

![屏幕截图 2023-06-22 054205](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/36002202/5222507f-bf0f-450d-a00d-9aa2d5accf61)

**Comment by Z-Siqi** [comment]
> 还有一处忘记说了，当日志级别改成“警告”后，关闭CFW窗口重新打开，“警告”就会变回成英文“warn”
> 
> ![屏幕截图 2023-06-22 054205](https://user-images.githubusercontent.com/36002202/247770712-5222507f-bf0f-450d-a00d-9aa2d5accf61.png)

这是一个来自原版的bug，故无法添加汉化

**Comment by Z-Siqi** [comment]
现在已经重新上传了release

**Comment by lianwensheng** [comment]
> > 还有一处忘记说了，当日志级别改成“警告”后，关闭CFW窗口重新打开，“警告”就会变回成英文“warn”
> > ![屏幕截图 2023-06-22 054205](https://user-images.githubusercontent.com/36002202/247770712-5222507f-bf0f-450d-a00d-9aa2d5accf61.png)
> 
> 这是一个来自原版的bug，故无法添加汉化

我是最近试用了BoyceLig的汉化补丁，发现没有这个问题，想着来顺带来反馈下，不过还是觉得你的翻译排版更好看，嘿嘿嘿

**Comment by Z-Siqi** [comment]
> > 还有一处忘记说了，当日志级别改成“警告”后，关闭CFW窗口重新打开，“警告”就会变回成英文“warn”
> > ![屏幕截图 2023-06-22 054205](https://user-images.githubusercontent.com/36002202/247770712-5222507f-bf0f-450d-a00d-9aa2d5accf61.png)
> 
> 这是一个来自原版的bug，故无法添加汉化

已在0.20.28解决这个的汉化问题
