### ISSUE TITLE
下载资料网络错误

### ISSUE THREAD

**Issue by jiyunfei12138** [Z-Siqi/Clash-for-Windows_Chinese#112]
### 你的问题/建议/想说的内容是什么?

![image](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/106957845/2e6135b7-9a29-41d0-b53b-faf5a5de733a)

### 版本

v 0.20.28 之前的版本突然就有了这个问题更新了还是有

**Comment by yyk725** [comment]
大哥你密钥露了也不打个码，不怕被别人拿去偷用？🤔
还有我觉得这不是clash的问题，是你这个链接挂了，你可以去官网重新拉个链接来试试

**Comment by Z-Siqi** [comment]
与Clash for Windows无关，建议向提供商寻求帮助
