### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ypcxjc715** [Z-Siqi/Clash-for-Windows_Chinese#117]
### 你的问题/建议/想说的内容是什么?

系统代理按钮无法点击，点击没有效果，
![image](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/121125376/097ddae0-bf44-4473-b0a2-e38e2f4e494d)
另外3个按钮可以点击，很奇怪，周日的下午突然就不好使了。

### 版本

0.20.30

**Comment by ypcxjc715** [comment]
感谢作者的付出，希望得到回复。

**Comment by Z-Siqi** [comment]
用原版的试试，如果也有问题就去原版的repo发issues

**Comment by ypcxjc715** [comment]
搞定了，我知道是啥问题了，我手动修改了cfw-settings.yaml文件，改错了，导致clash无法加载了。
