### ISSUE TITLE
那个文件苹果手机端可以用

### ISSUE THREAD

**Issue by OOOOuch** [Z-Siqi/Clash-for-Windows_Chinese#122]
### 你的问题/建议/想说的内容是什么?

苹果手机端有文件吗

### 版本

last

**Comment by Z-Siqi** [comment]
Clash for Windows 不支持 ios 端

**Comment by LuSuAllen** [comment]
Stash 有 iOS 和 macOS 端，可以使用 iCloud 同步配置文件
