### ISSUE TITLE
请问有手机版本的clash吗

### ISSUE THREAD

**Issue by chenlinglingling** [Z-Siqi/Clash-for-Windows_Chinese#128]
### 你的问题/建议/想说的内容是什么?

请问有手机版本的clash吗

### 版本

Nothing to preview

**Comment by Z-Siqi** [comment]
Android请自行前往Google Play Store下载
IOS暂未发现有Clash上架到App Store

**Comment by LuSuAllen** [comment]
iOS 版本可以使用付费的 Stash，和 Clash 用法一样。 @chenlinglingling
