### ISSUE TITLE
应用更新

### ISSUE THREAD

**Issue by twoone-3** [Z-Siqi/Clash-for-Windows_Chinese#134]
### 你的问题/建议/想说的内容是什么?

可否把应用内检查更新获取的几个的链接改为这个仓库的更新链接？
![image](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/62778573/6228c19b-d2d9-4ae9-8f55-6786ad018dbb)

### 版本

0.20.36

**Comment by OdinShiva** [comment]
我也想说能不能把打包名注明汉化，例如Clash.for.Windows.cn-0.20.36-win.zip

**Comment by Z-Siqi** [comment]
> 我也想说能不能把打包名注明汉化，例如Clash.for.Windows.cn-0.20.36-win.zip

我不觉得这么做有什么必要

**Comment by OdinShiva** [comment]
> > 我也想说能不能把打包名注明汉化，例如Clash.for.Windows.cn-0.20.36-win.zip
> 
> 我不觉得这么做有什么必要

因为每次更新的时候我都是把这里的和原版的cfw一起下载，然后就是一样的包名

**Comment by Z-Siqi** [comment]
> > > 我也想说能不能把打包名注明汉化，例如Clash.for.Windows.cn-0.20.36-win.zip
> > 
> > 
> > 我不觉得这么做有什么必要
> 
> 因为每次更新的时候我都是把这里的和原版的cfw一起下载，然后就是一样的包名

所以为什么要和原版的以前下载？
