### ISSUE TITLE
flash for windows 的service mode下载不成功

### ISSUE THREAD

**Issue by 897683541** [Z-Siqi/Clash-for-Windows_Chinese#135]
### 你的问题/建议/想说的内容是什么?

flash for windows 的service mode下载不成功
提示：Fail to install service
           User did not grant permission

### 版本

v.0.20.27

**Comment by Z-Siqi** [comment]
请使用原版再次测试，如果问题仍然存在，请向原版仓库进行反馈

**Comment by lucioussing** [comment]
我也是如此，fail to install,reload app也没用
