### ISSUE TITLE
你好请问下载set.up.020.37.exe版本为什么显示无法下载，需要授权？win11

### ISSUE THREAD

**Issue by 865411449** [Z-Siqi/Clash-for-Windows_Chinese#137]
### 你的问题/建议/想说的内容是什么?

请问下载set.up.020.37.exe版本为什么显示无法下载，需要授权？win11

### 版本

请问下载set.up.020.37.exe版本为什么显示无法下载，需要授权？win11

**Comment by Z-Siqi** [comment]
下载问题与Clash for Windows无关，换个浏览器试试？
