### ISSUE TITLE
將來有計劃支援繁體中文嗎？

### ISSUE THREAD

**Issue by ElliotCHEN37** [Z-Siqi/Clash-for-Windows_Chinese#138]
### 你的问题/建议/想说的内容是什么?

將來有計劃支援繁體中文嗎？

### 版本

-

**Comment by Z-Siqi** [comment]
考虑到台湾的中文使用习惯可能与中国不同，其次感觉Clash for Windows的用户应该主要都来自于中国，所以并不打算支持繁体中文。如果你想要繁体中文的话可以考虑选择自己翻译
