### ISSUE TITLE
关于更新的问题

### ISSUE THREAD

**Issue by bilibilizhiyicn** [Z-Siqi/Clash-for-Windows_Chinese#139]
### 你的问题/建议/想说的内容是什么?

就是在更新的时候，当下载好文件后，点击安装，他会安装出错，因为clash正在运行，但是在安装界面又关不掉，只能先通过任务管理器找到更新文件的路径，再把clash关了才能正常更新。
这个更新是兼容中文版的更新

### 版本

v0.20.38

**Comment by Z-Siqi** [comment]
预期的，目前更新前需要先关掉CFW再让安装程序执行安装，一部分是安装程序的问题

**Comment by bilibilizhiyicn** [comment]
对，我的预想是，安装程序可能没有写入自动关闭功能

**Comment by Z-Siqi** [comment]
> 对，我的预想是，安装程序可能没有写入自动关闭功能

如果你知道怎么做，可以去 [这里](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/blob/main/chinese_file/packing_script.iss) 添加/修改出可以正常自动关闭的封包脚本，然后再发个 Pull request。合并到主分支后的下个版本就会应用上这个更改
