### ISSUE TITLE
CFW 已停更，下一步是？

### ISSUE THREAD

**Issue by burningtnt** [Z-Siqi/Clash-for-Windows_Chinese#142]
感慨万千，不止从何说起 ……

**Comment by JSYRD** [comment]
R.I.P.

**Comment by Poempoat** [comment]
换其他gui的clash吧

**Comment by Laymanxu** [comment]
试试Clash Verge或者
Experimental-Clash/Clash.Net？
链接如下
https://github.com/zzzgydi/clash-verge/releases
https://github.com/ClashDotNetFramework/experimental-clash/releases
不过后者已经停更了

**Comment by maboloshi** [comment]
Clash.Net 约谈的更早🤣

**Comment by pjxxcc** [comment]
内核仓库已经没了

**Comment by Tikong** [comment]
我丢，刚用上

**Comment by Z-Siqi** [comment]
~下一步是把没了的线上文档给补上~
https://github.com/Z-Siqi/Clash-for-Windows_Chinese/wiki

**Comment by Aober1** [comment]
该咋用还是咋用
