### ISSUE TITLE
作者是否有原版的包呢？

### ISSUE THREAD

**Issue by CMEPCBHG** [Z-Siqi/Clash-for-Windows_Chinese#143]
### 催更

毕竟原作者已经删库了，没法下载了，如果能把原包发一下就好了。

**Comment by Aiyu-awa** [comment]
> ### 催更
> 毕竟原作者已经删库了，没法下载了，如果能把原包发一下就好了。

[clash-windows-amd64-v3-v1.18.0.zip](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/files/13243462/clash-windows-amd64-v3-v1.18.0.zip)

**Comment by Aiyu-awa** [comment]
> ### 催更
> 毕竟原作者已经删库了，没法下载了，如果能把原包发一下就好了。

我有一个Clash.for.Windows.Setup.0.20.36.exe

**Comment by agoodcoolman** [comment]
不敢传，怕。

**Comment by Bruce2173** [comment]
我刚看到有人保存分享了，比如这位（最新的0.20.39
https://github.com/dzvision/clash-for-windows-last

**Comment by Z-Siqi** [comment]
> ### 催更
> 毕竟原作者已经删库了，没法下载了，如果能把原包发一下就好了。

https://github.com/Z-Siqi/Clash-for-Windows_Chinese/releases/tag/CFW

**Comment by GreatDianna** [comment]
道理我都懂但是这儿的release里不是每次都放了7z和exe嘛
![](https://i0.hdslb.com/bfs/emote/107ebcbd4dd5895f4595ea6db963dc4566809c6e.png@60w_60h.webp)
