### ISSUE TITLE
clash版本对冲

### ISSUE THREAD

**Issue by 0xt0n** [Z-Siqi/Clash-for-Windows_Chinese#148]
### 你的问题/建议/想说的内容是什么?

先下了你的汉化版本，然后删了换了一个别的版本，两个版本都开了服务模式，好像对冲了。现在两个版本都不能联网，有什么办法可以重置吗？

### 版本

Clash.for.Windows.Setup.0.20.39.exe

**Comment by Z-Siqi** [comment]
没遇到过。建议在VMware之类的地方里开个虚拟机，然后在虚拟机里重现操作然后慢慢找该怎么解决问题，最后把有效的办法应用在主机上
