### ISSUE TITLE
silent start不生效

### ISSUE THREAD

**Issue by Abigorangee** [Z-Siqi/Clash-for-Windows_Chinese#150]
### 你的问题/建议/想说的内容是什么?

我使用的clash静默启动失效……原先是安装原版的0.20.28，今天更新了汉化0.20.39，静默启动都打开了，但是开机后还是会自动弹出主界面……搜了一下似乎没有人反映过这个问题，想请教一下是不是我哪里设置出错了？
![image](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/102571587/013fd357-6de0-47eb-97e5-037992151ebb)

### 版本

0.20.39

**Comment by Z-Siqi** [comment]
请在虚拟机里尝试安装并重现问题，然后把具体重现方式告诉我
