### ISSUE TITLE
silent start 在窗口最大化时不生效 

### ISSUE THREAD

**Issue by Abigorangee** [Z-Siqi/Clash-for-Windows_Chinese#154]
### 你的问题/建议/想说的内容是什么?

版本0.20.39，开启开机启动、开启clash时默认缩小到任务栏。

问题：在窗口最大化后，无论是否关闭面板（即最大化窗口再手动关闭窗口使其缩小到任务栏），重新启动后都会以窗口最大化的形式出现，不会自动缩小到任务栏。
如果只是普通打开窗口并且没有最大化，那么无论是打开窗口状态重启还是关闭窗口（缩小到任务栏）都可以正常的触发silent start。

### 版本

0.20.39

**Comment by allgoodWorld** [comment]
作者好像已经跑路避避风头了。
我也有这个疑问，感谢你提供的信息：如果只是普通打开窗口并且没有最大化，那么无论是打开窗口状态重启还是关闭窗口（缩小到任务栏）都可以正常的触发silent start，我折腾了好久终于在你这找到解决办法了，谢谢

**Comment by Abigorangee** [comment]
> 作者好像已经跑路避避风头了。 我也有这个疑问，感谢你提供的信息：如果只是普通打开窗口并且没有最大化，那么无论是打开窗口状态重启还是关闭窗口（缩小到任务栏）都可以正常的触发silent start，我折腾了好久终于在你这找到解决办法了，谢谢

其实也无关紧要吧，不太影响正常功能，偶然发现并且在重装之后试出了这个问题，关键核心估计是windows的锅？不论如何也很感谢原作者和汉化了，很实用的软件

**Comment by ShiraishiMa1** [comment]
https://clash-verge-rev.github.io/
用这个吧

**Comment by Z-Siqi** [comment]
应该是暂时修好了，但还在做其它测试 [试试?](https://t.me/SiqiChannel/40)

**Comment by Abigorangee** [comment]
> 应该是暂时修好了，但还在做其它测试 [试试?](https://t.me/SiqiChannel/40)

非常感谢！辛苦了！

**Comment by w12928293** [comment]
原来还跟最后的窗口大小有关，终于解决了，多谢多谢
