### ISSUE TITLE
Unanble to open GUI

### ISSUE THREAD

**Issue by MilleXi** [Z-Siqi/Clash-for-Windows_Chinese#156]
### 你的问题/建议/想说的内容是什么?

When connecting to a second monitor and drag the clash window to the second monitor, after dissconnecting the monitor, the Clash window will remain on that monitor and unable to display its gui.

### 版本

latest-release

**Comment by MRNOBODY-ZST** [comment]
Same problem too🤔
It seems that clash/windows will not actively reset the window setting after restart?

**Comment by Z-Siqi** [comment]
This issue cannot reproduce, maybe tell more details?
