### ISSUE TITLE
有没有适用于Linux系统的clash

### ISSUE THREAD

**Issue by ytanck** [Z-Siqi/Clash-for-Windows_Chinese#157]
### 催更

有没有适用于Linux系统的clash推荐额

**Comment by pangy9** [comment]
https://github.com/Elegycloud/clash-for-linux-backup

**Comment by ytanck** [comment]
开启clash之后，通过浏览器访问gpt网站是可以的，但是我想在项目里请求gpt的接口，并非是通过浏览器访问的，这种怎么实现呢

**Comment by sparkEchooo** [comment]
那就需要GPT的api了
