### ISSUE TITLE
订阅 token 被改变

### ISSUE THREAD

**Issue by Ming-er** [Z-Siqi/Clash-for-Windows_Chinese#159]
### 你的问题/建议/想说的内容是什么?

之前没有这个问题，最近突然遇到官网的订阅 token 不知道为什么会被改变（理论上订阅信息应该是一直不变的吧），因为梯子没了又没有办法去官网重新复制订阅地址，有朋友遇到这个问题吗？

### 版本

0.20.39

**Comment by Z-Siqi** [comment]
如果提 Issues 请至少描述如何重现这个问题，否则建议移步去 Discussions 创建一个讨论
