### ISSUE TITLE
dns配置异常

### ISSUE THREAD

**Issue by zhaotuo0815** [Z-Siqi/Clash-for-Windows_Chinese#160]
### 你的问题/建议/想说的内容是什么?

你好，我想问下，为什么我的edge需要用clash登陆vpn才能用啊？我把代理关掉，并且确定了网络设置的代理也关闭了就用不了浏览器，我联系电脑厂家，人家说是vpn的问题

### 版本

0.20.28

**Comment by Z-Siqi** [comment]
首先问题得可复现才谈得上能不能解决
