### ISSUE TITLE
下载资料失败什么原因

### ISSUE THREAD

**Issue by yyyy123921** [Z-Siqi/Clash-for-Windows_Chinese#161]
### 你的问题/建议/想说的内容是什么?

![屏幕截图 2024-07-08 000228](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/174954644/190630cd-7122-42f1-accf-554fb36fd0a2)

### 版本

汉化版

**Comment by Z-Siqi** [comment]
如题所述，502

还有，你发的图片把你的订阅地址public了，小心被别人盗用
