### ISSUE TITLE
Clash for Windows ARM64汉化补丁

### ISSUE THREAD

**Issue by Heramy** [Z-Siqi/Clash-for-Windows_Chinese#169]
电脑是Surface Pro X Windows ARM64，求汉化补丁。感恩感恩

**Comment by Z-Siqi** [comment]
https://github.com/Z-Siqi/Clash-for-Windows_Chinese/releases/download/CFW-V0.20.39_OPT-1/Clash.for.Windows-0.20.39-Opt.1-win32-arm64.7z

这个不能用吗？

**Comment by Heramy** [comment]
> https://github.com/Z-Siqi/Clash-for-Windows_Chinese/releases/download/CFW-V0.20.39_OPT-1/Clash.for.Windows-0.20.39-Opt.1-win32-arm64.7z
> 
> 
> 
> 这个不能用吗？

非常感谢，我之前查看是没有看到这个ARM版的，点进去老是404，太感谢您了，这是已经汉化后的ARM64的版本，直接压缩就可用，无需安装，之前安装的可以卸载了对吧？

**Comment by Z-Siqi** [comment]
可以
