### ISSUE TITLE
开启局域网接入Clash后 5分钟-2小时本地代理（localhost）会失效，只能通过局域网IP访问

### ISSUE THREAD

**Issue by zwl2000812** [Z-Siqi/Clash-for-Windows_Chinese#172]
### 你的问题/建议/想说的内容是什么?

这是我的测试，python通过localhost 7890访问效果如下
![image](https://github.com/user-attachments/assets/cc40b9b1-ba64-4c3a-8990-8724746b314e)

本地ip:7890访问效果如下
![image](https://github.com/user-attachments/assets/9cfdd61b-4b88-47eb-bdde-84625f6fab07)

通过修改系统的设置解决或者通过页面开关一次系统代理解决，不清楚是否是功能如此还是说开启局域网后localhost则访问不了了，或者我本地有特别的安全策略

### 版本

0.20.16.3

**Comment by Z-Siqi** [comment]
或许你可以用内核操作试试？如果用内核则没问题那么请告知一下
