### ISSUE TITLE
很诡异的一个域名被强制跳转的问题

### ISSUE THREAD

**Issue by chenm0520** [Z-Siqi/Clash-for-Windows_Chinese#174]
### 你的问题/建议/想说的内容是什么?

一个特定域名的请求被强制到一个无关域名了，如下图所示，上面3条是我请求chatgpt-test.chenm.xyz域名时的情况，下面3条是我请求chatgpt.chenm.xyz，都是同一个命令行请求的，可以看出chatgpt.chenm.xyz域名仿佛被劫持了一样，他打印的日志是直接从127.0.0.1发出的？然后请求了stnd-avpg.crsi.symantec.com，非常困惑。。
![1722236842094](https://github.com/user-attachments/assets/7f873ccf-e5ce-4aa3-91e2-aeeb52ab446c)

### 版本

V0.20.39-1

**Comment by Z-Siqi** [comment]
可能是你配置的问题。换全局再试试？

**Comment by chenm0520** [comment]
> 可能是你配置的问题。换全局再试试？

全局没有打印日志了，但是curl报了这个错误 curl: (56) Recv failure: Connection reset by peer
