### ISSUE TITLE
请问 yaml规则里的“-cn”是什么意思？

### ISSUE THREAD

**Issue by 1tonsilla** [Z-Siqi/Clash-for-Windows_Chinese#176]
### 你的问题/建议/想说的内容是什么?

我买了一个机场，最后的rule写的是：

```
    - 'DOMAIN-SUFFIX,cn,DIRECT'
    - 'DOMAIN-KEYWORD,-cn,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,守候网络'
``` 

关于   - 'DOMAIN-KEYWORD**,-cn,**DIRECT'，是否应该配置为“ - 'DOMAIN-KEYWORD,**.cn,**DIRECT'，”？
找了一些clash的配置，并没有找到  -cn是什么意思，问了CHATGPT，认为 -cn是排除cn，然后走DIRECT，很明显不符合逻辑，所以来请教一下，感谢~

### 版本

.

**Comment by Z-Siqi** [comment]
`- 'DOMAIN-KEYWORD,-cn,DIRECT'` 指的是如果网址里只要存在`-cn`就一律走直连。` 'DOMAIN-SUFFIX,cn,DIRECT'` 指的是如果网址是以`cn`结尾就走直连
