### ISSUE TITLE
无法切换到某些配置文件，不支持ss cipher?

### ISSUE THREAD

**Issue by ping678** [Z-Siqi/Clash-for-Windows_Chinese#177]
下载的配置文件切换时报错：无法切换到此配置文件
proxy27: 22 free.2weradf.xyz:36141 initialize error: cipher not supported

**Comment by YjZhang-sudo** [comment]
Me too, how did you solve this problem?

**Comment by Fan-Fan-Yang** [comment]
我也是这个提示，找不到解决办法

**Comment by YjZhang-sudo** [comment]
> 已知问题位置在 proxy27: 22，但具体需要你分享这个配置文件我才能去看具体问题是什么以及能不能解决

从哪看这个 proxy27:22的配；；置文件呢？

**Comment by Z-Siqi** [comment]
>
> 从哪看这个 proxy27:22的配；；置文件呢？

触发问题不是在切换配置的时候出现嘛，如果是那就得看出问题的这个配置文件里写的是什么

**Comment by ping678** [comment]
https://clashgithub.com/wp-content/uploads/rss/20240830.yml

**Comment by Z-Siqi** [comment]
> https://clashgithub.com/wp-content/uploads/rss/20240830.yml 这个配置文件可以看到，前几天的也有这个情况

配置文件里的字段：`cipher: ss,` 是无效语法，具体[参考这个](https://github.com/Z-Siqi/Clash-for-Windows_Rule/blob/main/template/README.md#shadowsocks-%E9%85%8D%E7%BD%AE%E6%A0%BC%E5%BC%8F)。问题与Clash无关

**Comment by dyslab** [comment]
> > https://clashgithub.com/wp-content/uploads/rss/20240830.yml 这个配置文件可以看到，前几天的也有这个情况
> 
> 配置文件里的字段：`cipher: ss,` 是无效语法，具体[参考这个](https://github.com/Z-Siqi/Clash-for-Windows_Rule/blob/main/template/README.md#shadowsocks-%E9%85%8D%E7%BD%AE%E6%A0%BC%E5%BC%8F)。问题与Clash无关

是的，问题出在这个带有 ` cipher: ss`  配置的 shadowsocket 节点上，由于 ss 节点的 cipher 配置没有 auto 选项，我目前的解决方式是下载 yaml 配置文件后，用记事本打开文件，全局查找 ` cipher: ss` 并将这些节点删除后保存即可使用，如果是程序抓取，可以考虑在导入 ss 节点时增加一个条件判断 cipher === ‘ss’ ，遇到此类节点跳过即可。

**Comment by wanghulouxia** [comment]
我遇到了类似的问题：proxy 11: ss hk04redir.ultra1stand.com:654 initialize error: cipher not supported
我自己解决的，也不清楚原理，就是把hk04关键字段的内容行及其涉及的端点删除了，比如
- { name: 'HKG A', type: ss, server: hk04redir.ultra1stand.com, port: 654, ----------- }和proxy-groups里的'HKG A.
然后就可以正常使用。
如果有用，就此做个记录了。
