### ISSUE TITLE
ubuntu 24.04 下 cfw v0.20.39 Opt-1 里为啥没有系统代理这个选项？

### ISSUE THREAD

**Issue by codebucket2021** [Z-Siqi/Clash-for-Windows_Chinese#179]
### 你的问题/建议/想说的内容是什么?

ubuntu 24.04 下 cfw v0.20.39 Opt-1 里为啥没有系统代理这个选项？
![image](https://github.com/user-attachments/assets/02fe1219-80c6-4952-9244-2be0adccdbb9)

### 版本

v0.20.39 Opt-1

**Comment by Z-Siqi** [comment]
因为原版的也没有
