### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by gongming598** [Z-Siqi/Clash-for-Windows_Chinese#182]
### 你的问题/建议/想说的内容是什么?

![360截图20240830115930602](https://github.com/user-attachments/assets/019b5681-24d2-40d1-87d4-899940208c05)
请问这个怎么解决？

### 版本

win.7z

**Comment by Z-Siqi** [comment]
从给出的信息来看是配置文件问题

**Comment by gongming598** [comment]
那怎么解决？

**Comment by Z-Siqi** [comment]
找提供配置文件的人

**Comment by gongming598** [comment]
![Clash 1](https://github.com/user-attachments/assets/1c6c7bf7-3eef-47c5-a8ec-d9424904f598)
好像就是来自于您，就是划线这个

**Comment by gongming598** [comment]
![Clash 2](https://github.com/user-attachments/assets/e4344e3f-f27b-4acf-9a64-21497575d802)
现在又出现了一个新问题

**Comment by Z-Siqi** [comment]
这看起来不是软件的问题，这个配置文件有问题

**Comment by gongming598** [comment]
应该是的
![Clash 3](https://github.com/user-attachments/assets/49373ed8-d53b-4145-9c69-5798167885ae)
我现在在试着更改这个
