### ISSUE TITLE
使用cmd启动clash；关闭cmd后clash也跟着关闭；这个是框架原因还是bug

### ISSUE THREAD

**Issue by yiyi940130** [Z-Siqi/Clash-for-Windows_Chinese#184]
### 你的问题/建议/想说的内容是什么?

使用cmd启动clash；关闭cmd后clash也跟着关闭；这个是框架原因还是bug
![image](https://github.com/user-attachments/assets/082b011f-9c1d-4a80-b02e-da51f39da8c3)

### 版本

![image](https://github.com/user-attachments/assets/72101033-4087-40b5-9e7f-2f9a77fbdd42)

**Comment by Xiao-yux** [comment]
不是bug，windows是这样的
