### ISSUE TITLE
已连接怎么没有显示 速率，是在哪里设置 

### ISSUE THREAD

**Issue by lyio067** [Z-Siqi/Clash-for-Windows_Chinese#188]
版本

**Comment by lyio067** [comment]
# Clash.for.Windows-0.20.39-Opt.1-linux-x64.tar.gz 版本  已连接怎么没有显示 速率，是在哪里设置 只能上内网
![截图_2024-09-23_02-17-56](https://github.com/user-attachments/assets/861ecfa4-79a6-47b2-9349-4d15cd04267c)

**Comment by Z-Siqi** [comment]
如果是在设置代理时遇到问题请参见 https://web.archive.org/web/20240906004644/https://docs.gtk.pw/contents/linux/linux-clash-gui.html (该说明现已添加在这个库的 [Wiki](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/wiki) 中以方便查询)
