### ISSUE TITLE
哪个版本的clash是兼容Win11的？

### ISSUE THREAD

**Issue by 86139USER** [Z-Siqi/Clash-for-Windows_Chinese#200]
### 你的问题/建议/想说的内容是什么?

下载了最新版的一直闪退，感觉是win11不兼容的问题

### 版本

no

**Comment by Z-Siqi** [comment]
由于这个问题在我这边的Windows11没有出现/复现，因此请提供更详细的信息（例如更详细的描述和详细系统版本，是否在beta或其它的更新channel）
