### ISSUE TITLE
打开应用闪退

### ISSUE THREAD

**Issue by FFkaddjh** [Z-Siqi/Clash-for-Windows_Chinese#202]
### 你的问题/建议/想说的内容是什么?

无法打开应用程序

### 版本

Clash.for.Windows.Setup.0.20.39_Opt-1.exe

**Comment by Z-Siqi** [comment]
系统是32位还是64位？CPU是Intel的还是AMD的？Windows的版本是什么？是否有在别的Windows更新channel？

**Comment by FFkaddjh** [comment]
64位 AMD     windows11家庭版    没有

**Comment by Z-Siqi** [comment]
由于我没有 AMD 的设备可用与测试，但是你可以尝试一下使用 https://github.com/Z-Siqi/Clash-for-Windows_Chinese/releases/download/CFW-V0.20.39_OPT-1/Clash.for.Windows-0.20.39-Opt.1-win32-arm64.7z 看看能不能用

**Comment by Yuiffy** [comment]
> 系统是32位还是64位？CPU是Intel的还是AMD的？Windows的版本是什么？是否有在别的Windows更新channel？

我这本来能用，有一天重启电脑后就一直用不了了，打开后右下角有几秒图标，然后就没了。intel 64位，windows 23H2 22631.4317。 体验 Windows Feature Experience Pack 1000.22700.1041.0

重新下了几个版本clash，也一样。

**Comment by larfchan** [comment]
症状一模一样，现在只能用clash verge和v2ray了。win11 23H2，8845H的CPU

**Comment by e1phie** [comment]
同样出现了这个bug，win11 24H2 26100.2314 amd的64位平台，某次重启后打开就出现闪退现象，重装无法解决

**Comment by Z-Siqi** [comment]
> 同样出现了这个bug，win11 24H2 26100.2314 amd的64位平台，某次重启后打开就出现闪退现象，重装无法解决

删掉`C:\Users\[user_name]\.config\clash\`, `C:\Users\[user_name]\AppData\Roaming\clash_win` (在此之前尽量把所有log发上来或许有助于找到问题), 和 `C:\Program Files\Clash for Windows Service\`(如果有) 下的所有文件试试？

**Comment by larfchan** [comment]
> > 同样出现了这个bug，win11 24H2 26100.2314 amd的64位平台，某次重启后打开就出现闪退现象，重装无法解决
> 
> 删掉`C:\Users\[user_name]\.config\clash\`, `C:\Users\[user_name]\AppData\Roaming\clash_win` (在此之前尽量把所有log发上来或许有助于找到问题), 和 `C:\Program Files\Clash for Windows Service\`(如果有) 下的所有文件试试？

尊敬的博主您好，我解决了：因为我用了一些小工具箱把“TCP网络拥塞控制开启BBR2”这个选项打开了。我把BBR2又关掉了就好了。

**Comment by larfchan** [comment]
> @larfchan 能请问一下用了什么工具吗？

Windows11轻松设置V1.09 (20240410)，应该是远景论坛找到的。或者你想想别的办法关掉这个BBR2看看
