### ISSUE TITLE
请问何时可以支持hysteria2协议

### ISSUE THREAD

**Issue by J-Ollie** [Z-Siqi/Clash-for-Windows_Chinese#205]
### 你的问题/建议/想说的内容是什么?

以后会更新支持hysteria2吗

### 版本

v0.20.39 Opt- 1

**Comment by Z-Siqi** [comment]
试试看这个？ https://github.com/kayaladream/Clash-Core-Change/tree/v2.0

**Comment by Z-Siqi** [comment]
See #276
