### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by CHAOZI22** [Z-Siqi/Clash-for-Windows_Chinese#206]
### 你的问题/建议/想说的内容是什么?

重装clash for windows后无法打开，双击快捷方式后任务栏会短暂出现clash图标，随即消失，后续没有任何反应。怀疑过卸载残留问题，已将文件名有关clash的文件夹都删除了，但还是没用。
大佬们，求解。

### 版本

0.20.39-1

**Comment by Z-Siqi** [comment]
具体重装的步骤是什么？（请在Windows Sandbox中复现该问题并提供复现步骤）
