### ISSUE TITLE
已仅为当前用户安装了原版的CFW, 想要汉化补丁

### ISSUE THREAD

**Issue by caoyirui** [Z-Siqi/Clash-for-Windows_Chinese#208]
### 你的问题/建议/想说的内容是什么?

请问是下载Clash.for.Windows.Setup.0.20.39_Opt-1.exe, 然后把安装目标文件夹改成我的本地用户安装位置(C:\Users\test\AppData\Local\Programs\Clash for Windows)就可以吗？

### 版本

V0.20.39

**Comment by Z-Siqi** [comment]
opt版本与V0.20.39并不兼容
