### ISSUE TITLE
Clash无法连接核心

### ISSUE THREAD

**Issue by wxhyc12** [Z-Siqi/Clash-for-Windows_Chinese#92]
你好，我这里安装的是20.22版本。我的电脑上始终显示“无法连接到clash core核心，日志不可用”。删除了根目录和安装目录重新安装也没有用。但是同样的clash安装在本机的虚拟机中又是可以使用的。个人推测可能是本机遗留的历史版本跟新安装的版本冲突。同时我也试过其他版本的汉化版和英文原版也是一样的提示。重置过网络也没有任何用。希望可以得到帮助非常感谢。

**Comment by Z-Siqi** [comment]
这种明显不是因汉化造成的问题请在查询Clash for Windows文档并确定无法解决后[前往官方repo发布Issues](https://github.com/Fndroid/clash_for_windows_pkg/issues)

此外，Windows Sandbox是无法正常运行代理的，你应该在Vware之类的虚拟机安装相同系统进行测试。

以你当前提供的信息可以尝试以下办法修复：
1. 尝试更新或恢复上一个系统和驱动
2. 尝试使用系统自带的扫描问题程序检查（例如设置中的疑难解答之类的选项）
3. 检查是否是因为权限或某些安全等软件问题所致，如果是那么请自行搜索解决方法
4. 尝试使用注册表和系统组件的修复软件检查问题并修复
5. 保留数据并重置你的PC
6. 不保留数据重置你的PC
7. 使用iso镜像重新安装系统

**Comment by wxhyc12** [comment]
好的非常感谢回复。之前无法连接核心的问题已经被我解决了，问题出在防火墙上。现在的问题只是不能切换自己的订阅链接包括下载，会直接提示无法切换配置Error：network error。这个问题我已经研究了挺久了目前还是没有找到解决办法。我的win10 的hyper虚拟机里的Clash倒是可以使用但是每次都要切换进去才能用步骤很繁琐。
