### ISSUE TITLE
安装clash中毒了

### ISSUE THREAD

**Issue by HB666666** [Z-Siqi/Clash-for-Windows_Chinese#96]
![5b48f325b72d87a8aa669b7886a41b4](https://github.com/Z-Siqi/Clash-for-Windows_Chinese/assets/110554291/fd8fb972-84be-4718-8e84-265b87677d33)
安装后，不知道为啥全变成clash图标，打开方式也变成打clash。。。。

**Comment by Z-Siqi** [comment]
可以去 Windows sandbox 里试试能不能重现错误，能的话再说

另外你的Windows是不是测试版？
然后把安装时Windows的log发来或许有帮助

**Comment by HB666666** [comment]
> 可以去 Windows sandbox 里试试能不能重现错误，能的话再说
> 
> 另外你的Windows是不是测试版？ 然后把安装时Windows的log发来或许有帮助

我感觉可能是win11环境问题，还好不是我电脑，我老师的。

**Comment by Z-Siqi** [comment]
Windows11 22621.1702 并无此问题，如果问题是由安装程序导致，请向 Inno Setup 反馈漏洞

**Comment by HB666666** [comment]
> Windows11 22621.1702 并无此问题，如果问题是由安装程序导致，请向 Inno Setup 反馈漏洞

老师安全意思有点低，没有给留样品，还是比较有点小遗憾。。。

**Comment by Z-Siqi** [comment]
~问题多半在360身上~ (猜的)

**Comment by HB666666** [comment]
> ~问题多半在360身上~ (猜的)

很有可能(*∩_∩*)
